name: AutoPack

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths:
    - Resourcepack/**

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Validator Config Path
  config_json: .github/configs/schema.json
  config_yaml: .github/configs/yaml-linter.yml

jobs:
  # Validator:
  #   name: "🔎 Validator ${{ matrix.PackName }}"
  #   runs-on: ubuntu-latest
  #   if: |
  #     contains(github.event.head_commit.message, 'chore: Publish') == false &&
  #     github.repository == 'xMikux/Slimefun-Resourcepack'

  #   strategy:
  #     matrix:
  #       include:
  #         - PackName: Minecraft
  #           Path_Models: Resourcepack/contents/_iainternal/resourcepack/assets/minecraft/**/*.json
  #         - PackName: Bump
  #           Path_Models: Resourcepack/contents/bump/resourcepack/bump/models/**/*.json
  #           Path_Pack: Resourcepack/contents/bump/configs/textures.yml
  #         - PackName: ExoticGarden
  #           Path_Models: Resourcepack/contents/exotic_garden/resourcepack/exotic_garden/models/**/*.json
  #           Path_Pack: Resourcepack/contents/exotic_garden/configs/textures.yml
  #         - PackName: ExtraGear
  #           Path_Models: Resourcepack/contents/extra_gear/resourcepack/extra_gear/models/**/*.json
  #           Path_Pack: Resourcepack/contents/extra_gear/configs/textures.yml
  #         - PackName: FluffyMachines
  #           Path_Models: Resourcepack/contents/fluffymachines/resourcepack/fluffymachines/models/**/*.json
  #           Path_Pack: Resourcepack/contents/fluffymachines/configs/textures.yml
  #         - PackName: FoxyMachines
  #           Path_Models: Resourcepack/contents/foxymachines/resourcepack/foxymachines/models/**/*.json
  #           Path_Pack: Resourcepack/contents/foxymachines/configs/textures.yml
  #         - PackName: InfinityExpansion
  #           Path_Models: Resourcepack/contents/infinityexpansion/resourcepack/infinityexpansion/models/**/*.json
  #           Path_Pack: Resourcepack/contents/infinityexpansion/configs/textures.yml
  #         - PackName: Litexpansion
  #           Path_Models: Resourcepack/contents/litexpansion/resourcepack/litexpansion/models/**/*.json
  #           Path_Pack: Resourcepack/contents/litexpansion/configs/textures.yml
  #         - PackName: SimpleUtils
  #           Path_Models: Resourcepack/contents/simpleutils/resourcepack/simpleutils/models/**/*.json
  #           Path_Pack: Resourcepack/contents/simpleutils/configs/textures.yml
  #         - PackName: Slimefun
  #           Path_Models: Resourcepack/contents/slimefun/resourcepack/slimefun/models/**/*.json
  #           Path_Pack: Resourcepack/contents/slimefun/configs/textures.yml
  #         - PackName: SlimefunWarfare
  #           Path_Models: Resourcepack/contents/slimefunwarfare/resourcepack/slimefunwarfare/models/**/*.json
  #           Path_Pack: Resourcepack/contents/slimefunwarfare/configs/textures.yml
  #         - PackName: SlimyTreeTaps
  #           Path_Models: Resourcepack/contents/slimy_tree_taps/resourcepack/slimy_tree_taps/models/**/*.json
  #           Path_Pack: Resourcepack/contents/slimy_tree_taps/configs/textures.yml
  #         - PackName: Supreme
  #           Path_Models: Resourcepack/contents/supreme/resourcepack/supreme/models/**/*.json
  #           Path_Pack: Resourcepack/contents/supreme/configs/textures.yml

  #   steps:
  #     - name: 📄 Checking Repostiory
  #       uses: actions/checkout@v3

  #     - name: ⚙ Validate YAML Files (${{ matrix.PackName }})
  #       if: "${{ matrix.Path_Pack != '' }}"
  #       uses: ibiqlik/action-yamllint@v3
  #       with:
  #         file_or_dir: ${{ matrix.Path_Pack }}
  #         config_file: ${{ env.config_yaml }}

  #     - name: ⚙ Validate JSON Files (${{ matrix.PackName }})
  #       if: "${{ matrix.Path_Models != '' }}"
  #       uses: nhalstead/validate-json-action@0.1.3
  #       with:
  #         schema: ${{ env.config_json }}
  #         jsons: ${{ matrix.Path_Models }}

  IAPack-Make:
    name: "✨ Make IAPack"
    # needs: Validator
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[ci skip]') == false

    steps:
      - name: 📄 Checking Repostiory
        uses: actions/checkout@v3

      - name: 🔒 Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: ⚡ Making IAPack 
        run: |
          mkdir output
          docker compose -f .github/compose/docker-compose.yml up
      
      - name: ✏️ Rename generated file
        run: |
          if [ -f "output/generated.zip" ]; then
            echo "Correctly generate resourcepack!"
            mv output/generated.zip IAGenerated.zip
          else
            echo "Not correctly generated resourcepack"
            exit 1
          fi

      - name: 📦 Upload IAGenerated Zip
        uses: actions/upload-artifact@v3
        with:
          name: IAGenerated
          path: IAGenerated.zip

      - name: 📦 Upload Item Models
        uses: actions/upload-artifact@v3
        with:
          name: Item-Models
          path: Resourcepack/item-models.yml

  IAPack-Place:
    name: "📌 IAPack Place"
    needs: IAPack-Make
    runs-on: ubuntu-latest

    steps:
      - name: 📄 Checking Repostiory
        uses: actions/checkout@v3
        with:
          ref: pack

      - name: ☁️ DownloadArtifact
        uses: actions/download-artifact@v3
        with:
          name: IAGenerated

      - name: 🗑️ Delete Artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: IAGenerated

      - name: 🔧 Replace Pack files
        run: |
          rm -r assets
          rm pack.mcmeta
          rm pack.png
          unzip IAGenerated.zip

      - name: 🔧 Remove unnecessary files
        run: |
          rm -r assets/_iainternal
          rm -r assets/minecraft/shaders
          rm -r assets/minecraft/blockstates
          rm -r assets/minecraft/font
          rm -r assets/minecraft/lang
          rm -r assets/minecraft/models/block
          rm -r assets/minecraft/models/item/base
          rm -r assets/minecraft/textures

      - name: 🧹 Cleanup IAGenerated
        run: |
          rm IAGenerated.zip

      - name: 🧰 Setup git config
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: 🎉 Commit and Push Pack
        continue-on-error: true
        run: |
          git add assets
          git add pack.mcmeta
          git add pack.png
          git commit -S -m "ci: Auto Texture Pack Update (${GITHUB_SHA::7})"
          git push origin pack

  Optimize-Pack:
    name: "📊 Optimize Pack"
    needs: IAPack-Place
    runs-on: ubuntu-latest

    steps:
      - name: 📄 Checking Repostiory
        uses: actions/checkout@v3
        with:
          ref: pack
          fetch-depth: 0

      - name: 📥 Package & Optimize Resourcepack
        uses: ComunidadAylas/PackSquash-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_optifine_mod: true
          never_store_squash_times: true
          artifact_name: Slimefun-ResourcePack
          path: ./

  Per-Release:
    name: "📢 Per Release"
    needs: Optimize-Pack
    runs-on: ubuntu-latest

    steps:
      - name: 📄 Checking Repostiory
        uses: actions/checkout@v3
      
      - name: ☁️ DownloadArtifact
        uses: actions/download-artifact@v3
        with:
          path: ./

      - name: ✅ Make Checksum
        run: |
          mv Slimefun-ResourcePack/pack.zip Slimefun-ResourcePack/Slimefun-ResourcePack.zip
          mv Slimefun-ResourcePack/Slimefun-ResourcePack.zip .
          mv item-models.yml item-model
          mv item-model/item-models.yml .
          SUM0=$(sha256sum Slimefun-ResourcePack.zip)
          SUM1=$(sha256sum item-models.yml)
          echo -e "$SUM0\n$SUM1" > checksums.txt

      - name: Create & Upload Per Releases 
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-build"
          prerelease: true
          title: "Beta Pack"
          files: |
            Slimefun-ResourcePack.zip
            item-models.yml
            checksums.txt

      - name: 🗑️ Delete Artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            Slimefun-ResourcePack
            Item-Models