name: AutoPack

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths:
    - Resourcepack/**
    - Default/minecraft/**
  schedule:
    - cron: "0 0 * * *"
  #  - cron: "0 0 * * 1"

env:
  panel_domain: ${{ secrets.DOMAIN }}
  # Builder-01
  server_uuid: SERVERUUID
  server_uuid_full: SERVERFULLUUID
  # Builder-02
  server_uuid_02: SERVERUUID_02
  server_uuid_full_02: SERVERFULLUUID_02
  # Sftp Info
  sftp_user: ${{ secrets.SFTP_USER }}
  sftp_pass: ${{ secrets.SFTP_PASS }}
  sftp_host: ${{ secrets.SFTP_HOST }}
  sftp_port: ${{ secrets.SFTP_PORT }}
  token: ${{ secrets.APIToken }}
  # Temporary Permission User
  cli_user: ${{ secrets.CLIUSERNAME }}
  cli_key: ${{ secrets.CLIKEY }}
  cli_port: ${{ secrets.CLIPORT }}
  cli_ip: ${{ secrets.CLIIP }}
  # Temporary Remove default.json
  # default_json: |
  #   {"providers":[]}

jobs:
  Validator:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[ci skip]') == false

    steps:
      - name: 📄 Checking Repostiory
        uses: actions/checkout@v2.0.0

      - name: ⚙ Validate JSON Files (minecraft)
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: .github/configs/schema.json
          jsons: |
            Default/minecraft/**/*.json

      - name: ⚙ Validate JSON Files (ExoticGarden)
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: .github/configs/schema.json
          jsons: |
            Resourcepack/resource_pack/assets/exotic_garden/models/**/*.json

      - name: ⚙ Validate JSON Files (InfinityExpansion)
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: .github/configs/schema.json
          jsons: |
            Resourcepack/resource_pack/assets/infinityexpansion/models/**/*.json

      - name: ⚙ Validate JSON Files (LiteXpansion)
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: .github/configs/schema.json
          jsons: |
            Resourcepack/resource_pack/assets/litexpansion/models/**/*.json

      - name: ⚙ Validate JSON Files (Slimefun)
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: .github/configs/schema.json
          jsons: |
            Resourcepack/resource_pack/assets/slimefun/models/slimefun/**/*.json

      - name: ⚙ Validate JSON Files (SlimyTreeTaps)
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: .github/configs/schema.json
          jsons: |
            Resourcepack/resource_pack/assets/slimy_tree_taps/models/**/*.json

  Daily-Pack:
    needs: Validator
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'schedule'

    steps:
      - name: 📄 Checking Repostiory
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0

      - name: Checking Repo Again
        run: |
          git fetch 
          git pull

      - name: 📥 Package & Optimize Resourcepack
        uses: ComunidadAylas/PackSquash-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./.pack

      - name: ☁ DownloadArtifact
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
          path: ./

      - name: 📝 Rename Resourcepack
        run: |
          mv ./pack.zip Slimefun-ResourcePack-Optimized.zip

      - name: Upload Optimized pack
        uses: actions/upload-artifact@v2
        with:
          name: Slimefun-ResourcePack-Optimized
          path: ./Slimefun-ResourcePack-Optimized.zip

      - name: Delete Optimized pack
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            Optimized pack

      - name: 📥 Zip Original Pack
        run: |
          zip -r Slimefun-ResourcePack-Original ./.pack/*

      - name: Upload Original pack
        uses: actions/upload-artifact@v2
        with:
          name: Slimefun-ResourcePack-Original
          path: Slimefun-ResourcePack-Original.zip

      - name: Upload Item Models
        uses: actions/upload-artifact@v2
        with:
          name: item-models.yml
          path: ./Resourcepack/item-models.yml

  Upload-Git-IAPack:
    name: "Upload-Git-IAPack (${{ matrix.name }})"
    needs: Validator
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'schedule'
    env:
      sv_uuid: ${{secrets[matrix.server_uuid]}}
      sv_uuid_full: ${{secrets[matrix.server_uuid_full]}}
    strategy:
      matrix:
       include:
         - name: "Original"
           server_uuid: SERVERUUID
           server_uuid_full: SERVERFULLUUID
         - name: "Optifine"
           server_uuid: SERVERUUID_02
           server_uuid_full: SERVERFULLUUID_02

    steps:
      - name: 📄 Checking Repostiory
        uses: actions/checkout@v2.0.0
      
      - name: 🗜 ZIP IAPack
        run: |
          mkdir workdir
          cp -r Resourcepack/items_packs workdir
          cp -r Resourcepack/resource_pack workdir
          cp -r Default/minecraft workdir/resource_pack/assets
          rm -r workdir/resource_pack/assets/minecraft/optifine
          tar --owner=pterodactyl --group=pterodactyl -cjf IAUpdate.tar.bz2 -C ./workdir .

      - name: 🗜 ZIP IAPack with "Optifine"
        if: |
          matrix.name == "Optifine"
        run: |
          rm IAUpdate.tar.bz2
          cp -r Default/minecraft workdir/resource_pack/assets
          tar --owner=pterodactyl --group=pterodactyl -cjf IAUpdate.tar.bz2 -C ./workdir .

      - name: ⚡ Upload IAPack to Server
        run: |
          curl -u "${{ env.sftp_user }}.${{ env.sv_uuid }}:${{ env.sftp_pass }}" \
          -T IAUpdate.tar.bz2 \
          -k "sftp://${{ env.sftp_host }}:${{ env.sftp_port }}/plugins/ItemsAdder/data/IAUpdate.tar.bz2"

      - name: ♻️ Delete Old IA Files
        run: |
          curl "https://${{ env.panel_domain }}/api/client/servers/${{ env.sv_uuid }}/files/delete" \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer ${{ env.token }}' \
          -X POST \
          -d '{
          "root": "/plugins/ItemsAdder/data/",
          "files": [
            "items_packs",
            "resource_pack"
            ]
          }'

      - name: 📤 UnArchive New IA Files
        run: |
          curl "https://${{ env.panel_domain }}/api/client/servers/${{ env.sv_uuid }}/files/decompress" \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer ${{ env.token }}' \
          -X POST \
          -d '{
          "root": "/plugins/ItemsAdder/data/",
          "file": "IAUpdate.tar.bz2"
          }'

      - name: ♻️ Cleanup Archive File
        run: |
          curl "https://${{ env.panel_domain }}/api/client/servers/${{ env.sv_uuid }}/files/delete" \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer ${{ env.token }}' \
          -X POST \
          -d '{
          "root": "/plugins/ItemsAdder/data/",
          "files": [
            "IAUpdate.tar.bz2"
            ]
          }'

      # Issues Link: https://github.com/pterodactyl/panel/issues/3689
      - name: 📁 Temporary using remote to fix folder permission
        uses: xMikux/ssh-action@master
        with:
          host: ${{ env.cli_ip }}
          username: ${{ env.cli_user }}
          key: ${{ env.cli_key }}
          port: ${{ env.cli_port }}
          script: |
            sudo chown -R pterodactyl:pterodactyl /var/lib/pterodactyl/volumes/${{ env.sv_uuid_full }}/plugins/ItemsAdder/data/

      - name: 💤 Sleep for 3 seconds
        run: sleep 3s

      - name: ⌘ IAReload Resourcepack
        run: |
          curl "https://${{ env.panel_domain }}/api/client/servers/${{ env.sv_uuid }}/command" \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer ${{ env.token }}' \
          -X POST \
          -d '{
          "command": "iareload"
          }'

      - name: 💤 Sleep for 3 seconds
        run: sleep 3s

      - name: ⌘ IAZip Resourcepack
        run: |
          curl "https://${{ env.panel_domain }}/api/client/servers/${{ env.sv_uuid }}/command" \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer ${{ env.token }}' \
          -X POST \
          -d '{
          "command": "iazip"
          }'

  Download-Server-Pack:
    name: "Download-Server-Pack (${{ matrix.name }})"
    needs: Upload-Git-IAPack
    runs-on: ubuntu-latest
    env:
      working-directory: ./.pack
      sv_uuid: ${{secrets[matrix.server_uuid]}}
      sv_uuid_full: ${{secrets[matrix.server_uuid_full]}}
    strategy:
      matrix:
       include:
         - name: "Original"
           server_uuid: SERVERUUID
           server_uuid_full: SERVERFULLUUID
         - name: "Optifine"
           server_uuid: SERVERUUID_02
           server_uuid_full: SERVERFULLUUID_02

    steps:
      - name: 📄 Checking Repostiory
        uses: actions/checkout@v2.0.0

      - name: 💤 Sleep for 5 seconds
        run: sleep 5s

      - name: 📥 Download ZIP Pack
        run: |
          curl -u "${{ env.sftp_user }}.${{ env.sv_uuid }}:${{ env.sftp_pass }}" \
          -k "sftp://${{ env.sftp_host }}:${{ env.sftp_port }}/plugins/ItemsAdder/data/resource_pack/pack.zip" \
          -o pack.zip
        working-directory: ${{ env.working-directory }}

      - name: 🔧 Replace Pack files
        run: |
          rm -r assets
          rm pack.mcmeta
          rm pack.png
          unzip pack.zip
          ls -alh
          mv pack.zip Slimefun-ResourcePack-${{ matrix.name }}.zip
        working-directory: ${{ env.working-directory }}

      - name: Upload ${{ matrix.name }} pack
        uses: actions/upload-artifact@v2
        with:
          name: Slimefun-ResourcePack-${{ matrix.name }}
          path: ./.pack/Slimefun-ResourcePack-${{ matrix.name }}.zip

      - name: Upload Item Models
        uses: actions/upload-artifact@v2
        with:
          name: item-models.yml
          path: ./Resourcepack/item-models.yml

      - name: 💤 Sleep for 2 seconds
        run: |
          rm ./.pack/Slimefun-ResourcePack-${{ matrix.name }}.zip
          sleep 2s

      - name: 🧰 Setup git config
        if: |
          matrix.name != "Optifine"
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      # Temporary Remove default.json
      - name: Temporary Remove default.json
        run: |
          rm assets/minecraft/font/default.json
        working-directory: ${{ env.working-directory }}

      - name: 🎉 Commit and Push Pack
        continue-on-error: true
        if: |
          matrix.name != "Optifine"
        run: |
          export CURRENTTIME=$( TZ=":Asia/Taipei" date '+%Y-%m-%d %R %Z' )
          git add assets
          git add pack.mcmeta
          git add pack.png
          git commit -S -m "⭐ New Texturepack Upload $CURRENTTIME"
          git push origin main
        working-directory: ${{ env.working-directory }}

  Pack-Resourcepack:
    name: "Pack-Resourcepack (${{ matrix.name }})"
    needs: Download-Server-Pack
    runs-on: ubuntu-latest
    env:
      sv_uuid: ${{secrets[matrix.server_uuid]}}
      sv_uuid_full: ${{secrets[matrix.server_uuid_full]}}
    strategy:
      matrix:
       include:
         - name: "Original"
           server_uuid: SERVERUUID
           server_uuid_full: SERVERFULLUUID
         - name: "Optifine"
           server_uuid: SERVERUUID_02
           server_uuid_full: SERVERFULLUUID_02

    steps:
      - name: 📄 Checking Repostiory
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0

      - name: Checking Repo Again
        run: |
          git fetch 
          git pull

      - name: Download Optifine Version Pack
        if: |
          matrix.name == "Optifine"
        run: |
          rm -r assets
          rm pack.mcmeta
          rm pack.png
          curl -u "${{ env.sftp_user }}.${{ env.sv_uuid }}:${{ env.sftp_pass }}" \
          -k "sftp://${{ env.sftp_host }}:${{ env.sftp_port }}/plugins/ItemsAdder/data/resource_pack/pack.zip" \
          -o pack.zip
          unzip pack.zip
          ls -alh
          ls -alh .pack\assets\minecraft
          rm pack.zip
          rm assets/minecraft/font/default.json
        working-directory: ./.pack

      - name: 📥 Package & Optimize Resourcepack
        uses: ComunidadAylas/PackSquash-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./.pack

      - name: ☁ DownloadArtifact
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
          path: ./

      - name: 📝 Rename Resourcepack
        run: |
          mv ./pack.zip Slimefun-ResourcePack-Optimized-${{ matrix.name }}.zip

      - name: Upload Optimized pack
        uses: actions/upload-artifact@v2
        with:
          name: Slimefun-ResourcePack-Optimized-${{ matrix.name }}
          path: ./Slimefun-ResourcePack-Optimized-${{ matrix.name }}.zip

      - name: Rename Optimized pack
        continue-on-error: true
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            Optimized pack
