name: CI_Release

on:
  push:
    tags:
      - "v*"

jobs:
  Create-Release:
    runs-on: ubuntu-latest

    steps:
      - name: 📄 Checking Repostiory
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0

      - name: Bump Up Version
        env:
          TAG: ${{ github.ref }}
        run: |
          TAGNAME=${TAG:10}
          sed -i 's/Beta/Release/1' .pack/pack.mcmeta
          sed -i 's/v[0-9].[0-9]/'$TAGNAME'/1' .pack/pack.mcmeta
          cat .pack/pack.mcmeta

      - name: Make Original Pack
        run: |
          cd .pack
          zip -r Slimefun-ResourcePack-Original assets/* pack.mcmeta pack.png

      - name: Move Original Pack & Item models
        run: |
          mv Resourcepack/item-models.yml .
          mv .pack/Slimefun-ResourcePack-Original.zip .
      
      - name: Make Original Optimized Pack
        uses: ComunidadAylas/PackSquash-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./.pack

      - name: ☁ DownloadArtifact Original Optimized Pack
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
          path: ./

      - name: 📝 Rename Original Optimized Pack
        run: |
          mv ./pack.zip Slimefun-ResourcePack-Optimized-Original.zip

      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            Optimized pack

      - name: Make Checksum
        run: |
          SUM=$(sha256sum Slimefun-ResourcePack-Original.zip)
          SUM1=$(sha256sum Slimefun-ResourcePack-Optimized-Original.zip)
          echo -e "$SUM\n$SUM1" > checksum.txt

      - name: Create & Upload Releases 
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            Slimefun-ResourcePack-Original.zip
            Slimefun-ResourcePack-Optimized-Original.zip
            item-models.yml
            checksum.txt
