name: Resuable | GitHub Release

on:
  workflow_call:
    inputs:
      release_type:
        type: string
        required: false
        default: "beta"

jobs:
  github_release:
    name: Release GitHub
    runs-on: ubuntu-latest
    steps:
      - name: abc
        run: |
          abc